efcoreApp/Models/KursViewModel.cs
using System.ComponentModel.DataAnnotations;
using efcoreApp.Data;

namespace efcoreApp.Models
{
    public class KursViewModel
    {
        public int KursId { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Kurs Baslığı")]
        public string? Baslik { get; set; }
        public int OgretmenId { get; set; }
        public ICollection<KursKayit> KursKayitlari { get; set; } = new List<KursKayit>();
    }
}

efcoreApp/Controllers/KursController.cs
using System.Threading.Tasks;
using efcoreApp.Data;
using efcoreApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class KursController:Controller
    {
       private readonly DataContext _context;
       public KursController (DataContext context)
       {
         _context=context;
       }
        public async Task<IActionResult> index()
        {
            return View(await _context.Kurslar.Include(k=>k.Ogretmen).ToListAsync());
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Ogretmenler=new SelectList(await _context.Ogretmenler.ToListAsync(),"OgretmenId","AdSoyad");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(KursViewModel model)
        {
            if(ModelState.IsValid)
            {
                _context.Kurslar.Add(new Kurs() { KursId = model.KursId, Baslik = model.Baslik, OgretmenId = model.OgretmenId });
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Ogretmenler = new SelectList(await _context.Ogretmenler.ToListAsync(), "OgretmenId", "AdSoyad");
            return View(model);

        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Ogr = await _context
                            .Kurslar
                            .Include(k=>k.KursKayitlari)
                            .ThenInclude(k=>k.Ogrenci)
                            .Select(k=>new KursViewModel
                            {
                                KursId=k.KursId,
                                Baslik=k.Baslik,
                                OgretmenId=k.OgretmenId,
                                KursKayitlari=k.KursKayitlari
                            })
                            .FirstOrDefaultAsync(k=>k.KursId==id);
            // var Ogr = await _context.Ogrenciler.FirstOrDefaultAsync(o=>o.OgrenciId==id);
            if (Ogr == null)
            {
                return NotFound();
            }
            ViewBag.Ogretmenler = new SelectList(await _context.Ogretmenler.ToListAsync(), "OgretmenId", "AdSoyad");
            return View(Ogr);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, KursViewModel model)

        {
            if (id != model.KursId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(new Kurs(){KursId=model.KursId,Baslik=model.Baslik,OgretmenId=model.OgretmenId});
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Kurslar.Any(o => o.KursId == model.KursId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewBag.Ogretmenler = new SelectList(await _context.Ogretmenler.ToListAsync(), "OgretmenId", "AdSoyad");
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Ogrenci = await _context.Kurslar.FindAsync(id);
            if (Ogrenci == null)
            {
                return NotFound();
            }
            return View(Ogrenci);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id)
        {
            var kurs = await _context.Kurslar.FindAsync(id);
            if (kurs == null)
            {
                return NotFound();
            }
            _context.Kurslar.Remove(kurs);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

efcoreApp/Views/Kurs/Create.cshtml
@model KursViewModel
    <h2>Kurs Ekle</h2>
    <hr>
<form asp-controller="Kurs" asp-action="Create" method="post">
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="Baslik" class="form-label"></label>
        <input asp-for="Baslik" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="OgretmenId" class="form-label">Öğretmen</label>
        <select asp-for="OgretmenId" asp-items="ViewBag.Ogretmenler" class="form-select">
            <option value="">Seciniz</option>
        </select>
    </div>
    
    <button type="submit" class="btn btn-secondary">Kaydet</button>
    
</form>

efcoreApp/Views/Kurs/Delete.cshtml
@model Kurs
<p>
    <b>@Model.Baslik </b> isimli kursu silmek istiyor musun?
    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.KursId" name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a>
    </form>
</p>

efcoreApp/Views/Kurs/Edit.cshtml
@model KursViewModel
<h2>Kurs Güncelleme</h2>
<hr>
<div class="row">
    <div class="col-8">
        <form asp-controller="Kurs" asp-action="Edit" method="post">
            <div asp-validation-summary="All"></div>
            <input type="hidden" asp-for="KursId">
            <div class="mb-3">
                <label asp-for="Baslik" class="form-label"></label>
                <input asp-for="Baslik" class="form-control">
            </div>

            <div class="mb-3">
                <label asp-for="OgretmenId" class="form-label">Öğretmen</label>
                <select asp-for="OgretmenId" asp-items="ViewBag.Ogretmenler" class="form-select">
                    <option value="">Seciniz</option>
                </select>
            </div>

            <button type="submit" class="btn btn-secondary">Kaydet</button>
        
        </form>
    </div>
    <div class="col-4">

        <h4>Öğrenciler</h4>
        <hr>
        <ul>
            @foreach(var item in @Model.KursKayitlari)
            {
                <li>@item.Ogrenci.AdSoyad</li>
            }
        </ul>
    </div>
</div>

efcoreApp/Views/Kurs/Index.cshtml
@model IEnumerable<Kurs>
<table class="table table-bordered">
    <h2>Kurs Listesi</h2>
    <a href="/Kurs/Create" class="btn btn-primary">Kurs Ekle</a>
    <hr>
    <thead>
        <tr>
            <th tyle="width: 150px;">@Html.DisplayNameFor(m=>m.KursId)</th>
            <th>@Html.DisplayNameFor(m=>m.Baslik)</th>
            <th>@Html.DisplayNameFor(m=>m.Ogretmen.AdSoyad)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
               <td>@Html.DisplayFor(modelItem=> item.KursId)</td>
               <td>@Html.DisplayFor(modelItem=> item.Baslik)</td>
               <td>@Html.DisplayFor(modelItem=> item.Ogretmen.AdSoyad)</td>
               <td>
                <a asp-controller="Kurs" asp-action="Edit" asp-route-id="@item.KursId" class="btn btn-sm btn-primary">Edit</a>
                <a asp-controller="Kurs" asp-action="Delete" asp-route-id="@item.KursId" class="btn btn-sm btn-danger">Delete</a>
               </td>
            </tr>
        }
    </tbody>
</table>