efcoreApp/Controllers/OgrenciController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class OgrenciController:Controller
    {
        private readonly DataContext _context;
        public OgrenciController(DataContext context)
        {
            _context=context;
        }
        public async Task<IActionResult> index()
        {
            return View(await _context.Ogrenciler.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Ogrenci model)
        {
            _context.Ogrenciler.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var Ogr = await _context
                            .Ogrenciler
                            .Include(o=>o.KursKayitlari)
                            .ThenInclude(o=>o.Kurs)
                            .FirstOrDefaultAsync(o=>o.OgrenciId==id);
            // var Ogr = await _context.Ogrenciler.FirstOrDefaultAsync(o=>o.OgrenciId==id);
            if (Ogr == null)
            {
                return NotFound();
            }
            return View(Ogr);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Ogrenci model)

        {
            if(id!=model.OgrenciId)
            {
                return NotFound();
            }
            if(ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if(!_context.Ogrenciler.Any(o=>o.OgrenciId==model.OgrenciId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var Ogrenci=await _context.Ogrenciler.FindAsync(id);
            if(Ogrenci==null)
            {
                return NotFound();
            }
            return View(Ogrenci);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int id)
        {
            var Ogrenci=await _context.Ogrenciler.FindAsync(id);
            if(Ogrenci==null)
            {
                return NotFound();
            }
            _context.Ogrenciler.Remove(Ogrenci);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
    
    
}

efcoreApp/Views/Ogrenci/Create.cshtml
@model Ogrenci
    <h2>Öğrenci Ekle</h2>
    <hr>
<form asp-controller="Ogrenci" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciAd" class="form-label"></label>
        <input asp-for="OgrenciAd" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="OgrenciSoyad" class="form-label"></label>
        <input asp-for="OgrenciSoyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label"></label>
        <input asp-for="Eposta" class="form-control">
    </div>
        
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label"></label>
        <input asp-for="Telefon" class="form-control">
    </div>
    <button type="submit" class="btn btn-secondary">Kaydet</button>
    
</form>

efcoreApp/Views/Ogrenci/Delete.cshtml
@model Ogrenci
<p>
    <b>@Model.OgrenciAd @Model.OgrenciSoyad</b> İsimli öğrenciyi silmek istiyor musun?
    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.OgrenciId" name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a>
    </form>
</p>

efcoreApp/Views/Ogrenci/Edit.cshtml
@model Ogrenci
<h2>Öğrenci Öğrenci Güncelleme</h2>
<hr>
<div class="row">
    <div class="col-8">
        <form asp-controller="Ogrenci" asp-action="Edit" method="post">
            <input type="hidden" asp-for="OgrenciId">
            <div class="mb-3">
                <label asp-for="OgrenciAd" class="form-label"></label>
                <input asp-for="OgrenciAd" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="OgrenciSoyad" class="form-label"></label>
                <input asp-for="OgrenciSoyad" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Eposta" class="form-label"></label>
                <input asp-for="Eposta" class="form-control">
            </div>
        
            <div class="mb-3">
                <label asp-for="Telefon" class="form-label"></label>
                <input asp-for="Telefon" class="form-control">
            </div>
            <button type="submit" class="btn btn-secondary">Kaydet</button>
        
        </form>
    </div>
    <div class="col-4">
        <h4>Kurslar</h4>
        <hr>
        <ul>
            @foreach(var item in @Model.KursKayitlari)
            {
                <li>@item.Kurs.Baslik</li>
            }
        </ul>
    </div>
</div>

efcoreApp/Views/Ogrenci/Index.cshtml
@model IEnumerable<Ogrenci>
<table class="table table-bordered">
    <h2>Öğrenci Listesi</h2>
    <a href="/Ogrenci/Create" class="btn btn-primary">Öğrenci Ekle</a>
    <hr>
    <thead>
        <tr>
            <th tyle="width: 150px;">@Html.DisplayNameFor(m=>m.OgrenciId)</th>
            <th>@Html.DisplayNameFor(m=>m.OgrenciAd)</th>
            <th>@Html.DisplayNameFor(m=>m.OgrenciSoyad)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var Ogrenci in Model)
        {
            <tr>
               <td>@Html.DisplayFor(modelItem=> Ogrenci.OgrenciId)</td>
               <td>@Html.DisplayFor(modelItem=> Ogrenci.OgrenciAd)</td>
               <td>@Html.DisplayFor(modelItem=> Ogrenci.OgrenciSoyad)</td>
               <td>
                <a asp-controller="Ogrenci" asp-action="Edit" asp-route-id="@Ogrenci.OgrenciId" class="btn btn-sm btn-primary">Edit</a>
                <a asp-controller="Ogrenci" asp-action="Delete" asp-route-id="@Ogrenci.OgrenciId" class="btn btn-sm btn-danger">Delete</a>
               </td>
            </tr>
        }
    </tbody>
</table>