efcoreApp/Controllers/KursKayitController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class KursKayitController:Controller
    {
        private readonly DataContext _context;
        public KursKayitController(DataContext context)
        {
            _context=context;
        }
        public async Task<IActionResult> Index()
        {
            var KursKayit=await _context
                        .KursKayit
                        .Include(x=>x.Ogrenci)
                        .Include(x=>x.Kurs)
                        .ToListAsync();
            return View(KursKayit);
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Ogrenciler=new SelectList(await _context.Ogrenciler.ToListAsync(),"OgrenciId","AdSoyad");
            ViewBag.Kurslar= new SelectList(await _context.Kurslar.ToListAsync(),"KursId","Baslik");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(KursKayit model)
        {
            model.KayitTarihi=DateTime.Now;
            _context.KursKayit.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

efcoreApp/Views/KursKayit/Create.cshtml
@model KursKayit
    <h2>Kurs Kayit</h2>
    <a asp-action="Create" class="btn btn-primary">Kayit Ekle</a>
    <hr>
<form asp-controller="KursKayit" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciId" class="form-label">Ogrenci</label>
        <select asp-for="OgrenciId" asp-items="ViewBag.Ogrenciler" class="form-control">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="KursId" class="form-label">Kurs</label>
        <select asp-for="KursId" asp-items="ViewBag.Kurslar" class="form-select">
            <option value="">Seçiniz</option>
        </select>
    </div>

    <button type="submit" class="btn btn-secondary">Kaydet</button>
    
</form>

efcoreApp/Views/KursKayit/Index.cshtml
@model IEnumerable<KursKayit>

<h2>Öğrençi Listesi</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m=>m.KayitId)</th>
            <th >@Html.DisplayNameFor(m=>m.Ogrenci.OgrenciAd)</th>
            <th>@Html.DisplayNameFor(m=>m.Kurs.Baslik)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelitem=>item.KayitId)</td>
                <td>@Html.DisplayFor(modelitem=>item.Ogrenci.OgrenciAd)</td>
                <td>@Html.DisplayFor(modelitem=>item.Kurs.Baslik)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.OgrenciId" class="btn btn-sm btn-primary">Edit</a>
                    <a  asp-action="Delete" asp-route-id="@item.OgrenciId"
                        class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>