MeetingApp/Models/Meetinginfo.cs
namespace MeetingApp.Models
{
    public class Meetinginfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }
        public int NumberofPeople { get; set; }

    }
}

MeetingApp/Models/Repository.cs
namespace MeetingApp.Models
{
    public static class Repository
    {
        private static List<Userinfo>_users=new();
        static Repository()
        {
            _users.Add(new Userinfo(){ Id=1, Name = "Ali",Email="abc@gmail.com", Phone="0255",WillAttend=true});
            _users.Add(new Userinfo() { Id = 2, Name = "Ahmet", Email = "abcd@gmail.com", Phone = "02552", WillAttend = false });
            _users.Add(new Userinfo() { Id = 3, Name = "Canan", Email = "abce@gmail.com", Phone = "02553", WillAttend = true });


        }
        public static List<Userinfo> Users
        {
            get
            {
                return _users;
            }
        }
        public static void CreateUser(Userinfo user)
        {
            user.Id=Users.Count+1;
            _users.Add(user);
        }
        public static Userinfo? GetById(int id)
        {
            return _users.FirstOrDefault(user=> user.Id==id);
        }
        
    }
}

MeetingApp/Models/Userinfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{
    public class Userinfo
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Ad alanı zorunlu")]
        public string? Name { get; set; }
        [Required(ErrorMessage = "Telefon alanı zorunlu")]
        public string? Phone { get; set; }
        [Required(ErrorMessage = "Eposta alanı zorunlu")]
        [EmailAddress(ErrorMessage = "Hatalı E-mail")]
        public string? Email { get; set; }
        [Required(ErrorMessage = "katıl durumunuzu Belirtiniz")]
        public bool? WillAttend { get; set; }
    }
}

MeetingApp/Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController: Controller
    {
        //localhost/
        //localhost/home
        // localhost/home/index
        public IActionResult Index()
        {

            int saat = DateTime.Now.Hour;
            // ViewBag.selamlama= saat > 12 ? "iyi günler" : "Günaydın";
            // ViewBag.UserName="Mehmet";
            ViewData["selamlama"]= saat > 12 ? "iyi günler" : "Günaydın";
             int UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();
            // ViewData["UserName"]= "Vehbi";
            var meetinginfo=new Meetinginfo()
            {
                Id=1,
                Location="Konya selçuklu kongre merkezi",
                Date=new DateTime(2025,12,10,10,0,0),
                NumberofPeople= UserCount
            };
            return View(meetinginfo);
        }
    }
}

MeetingApp/Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {
        // GET: MeetingController
        [HttpGet]
        public IActionResult Apply()
        {
            return View();
        }
       
        [HttpPost]
        public IActionResult Apply(Userinfo model)
        {
            if(ModelState.IsValid)
            {
                Repository.CreateUser(model);
                ViewBag.UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();
                return View("Thanks", model);
            }
            else
            {
                return View(model);
            }
        
        }
        [HttpGet] //Get requets'si
        public IActionResult List()
        {
            
            return View(Repository.Users);
        }
        
        [HttpGet]
        public IActionResult Details(int id)
        {
            return View (Repository.GetById(id));
        }

    }
    
}

MeetingApp/Views/Home/Index.cshtml
@model Meetinginfo
@{
    ViewBag.Title = "Başvuru Başvuru";
    Layout ="_Layout2";
}
<main class="text-center">
    <h1 class="h4">@ViewData["selamlama"]</h1>
    <p>Toplantıya katılım durumunu bildiriniz.</p>
    
    <div class="card my-2">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">@Model.Location</li>
            <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") Tarihinde gerçekleşecek</li>
            <li class="list-group-item">@Model.NumberofPeople Katılımcı</li>
        </ul>
    </div>
    <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvuru Yap</a>
</main>

MeetingApp/Views/Meeting/Apply.cshtml
@model Userinfo
@{
    ViewBag.Title="Toplantı Başvuru";

}
<h1 class="h4 text-center">Toplantı katılım formu</h1>
<form method="post" action="/meeting/apply" novalidate>
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Ad Soyad</label>
        <input asp-for="Name" class="form-control">
      
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Telefon</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Eposta</label>
        <input asp-for="Email" class="form-control">
    
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">katılım Durumu</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">seçiniz</option>
            <option value="true">Evet Geliyorum</option>
            <option value="false">Hayır Gelmiyorum</option>
        </select>
    
    </div>
    <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

MeetingApp/Views/Meeting/Details.cshtml
@model Userinfo
@{
    ViewBag.Title="Başvuru Detayı";
}
@{
    var className=@Model.WillAttend == true ? "primary":"danger";
}
<Main class="text-center">
    <h1 class="h4">Başvuru Detayı</h1>
    <p>
        <span class="badge text-bg-@className">@if(Model.WillAttend==true)
            {
                <text>Katılıyor</text>
            }else
            {
                <text>Katımıyor</text>
            }
        </span>
        
    </p>
    <p>isim:@Model.Name</p>
    <p>isim:@Model.Email</p>
    <p>Telefon:@Model.Phone</p>
    <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katılımcı Listesi</a>

</Main>

MeetingApp/Views/Meeting/List.cshtml
@model List<Userinfo>
@{
    ViewBag.Title="Toplantı Katılım listesi";

}
<main class="text-center">
    <h1 class="h4">Toplantıya Katılım listesi</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Ad</td>
                <td>Katılım Durumu</td>
                <td></td>
    
            </tr>
        </thead>
        <tbody>
            @{
                int i=0;
            }
            @foreach(var user in Model){
                var durum=user.WillAttend == true ? "evet":"Hayır";
                var className= user.WillAttend== true? "table-success":"table-danger";

                if (user.WillAttend==true){
                    i++;
                }
                <tr class="@className">
                    <td>@user.Name</td>
                    <td>@durum</td>
                    <td>             
                        <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
                     </td>        
                </tr>        
            }
        </tbody>
    </table>
    <div class="card">
        <div class="card-body">
            <p>Katılımcı sayısı: @i</p>
        </div>
    </div>

</main>

MeetingApp/Views/Meeting/Thanks.cshtml
@model Userinfo
@{
    ViewBag.Title="Başvuru özeti";

}
<main class="text-center">
    <h1 class="h4">Başvuru özeti</h1>
    @if(Model.WillAttend==true)
    {
        <p>,Teşekkürler, @Model.Name toplantıya sizinle birlikte @ViewBag.UserCount kaç kişi katılıyor.</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>

    }else
    {
        <p>@Model.Name, Katılmadığında üzgünüz</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru Formu</a>
    }
    
</main>